### ISSUE TITLE
Please consider merging your work

### ISSUE THREAD

**Issue by pcav** [gis3w/geoscopio_search#1]
Probably adding Geoscopio as a service to one of the existing service providers would make life easier for both users and developers.

**Comment by giohappy** [comment]
The plugin is meant as an interface to a web client where the RT SDI Department will publish various search tools. It isn't meant to substitute standard catalog providers (like CWS).

**Comment by pcav** [comment]
Got it, thanks.

**Comment by giohappy** [comment]
The plugin is meant as an interface to a web client where the RT SDI
Department will publish various search tools. It isn't meant to substitute
standard catalog providers (like CWS).

Il 21 ott 2016 13:31, "Paolo Cavallini" notifications@github.com ha
scritto:
