### ISSUE TITLE
Crash Qgis

### ISSUE THREAD

**Issue by lorex82** [gis3w/geoscopio_search#2]
Appena installato il plugin su Ubuntu 16.04 64 bit qgis 2.16.1 qgis si chiude immediatamente. Se provo a riaprire qgis, il programma si chiude al momento in cui carica i plugin. riporto i comandi della shell

lorex@Lorex:~$ qgis
Warning: loading of qt translation failed [/usr/share/qt4/translations/qt_it_IT]
Warning: QCss::Parser - Failed to load file  "/style.qss" 
QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed: File o directory non esistente
Warning: QFileSystemWatcher: failed to add paths: /home/lorex/.qgis2//project_templates
Warning: QLayout: Attempting to add QLayout "" to QgsPanelWidgetStack "mWidgetStack", which already has a layout
lorex@Lorex:~$ qgis
Warning: loading of qt translation failed [/usr/share/qt4/translations/qt_it_IT]
Warning: QCss::Parser - Failed to load file  "/style.qss" 
QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed: File o directory non esistente
Warning: QFileSystemWatcher: failed to add paths: /home/lorex/.qgis2//project_templates
Warning: QLayout: Attempting to add QLayout "" to QgsPanelWidgetStack "mWidgetStack", which already has a layout
Warning: Object::connect: No such signal QWebPage::loadProgress(int)
Warning: Object::connect: No such signal QWebPage::unsupportedContent(QNetworkReply*)
Warning: Object::connect: No such signal QWebFrame::titleChanged(QString)
Warning: Object::connect: No such signal QWebPage::loadProgress(int)
Warning: Object::connect: No such signal QWebFrame::titleChanged(QString)
Warning: Object::connect: No such signal QWebFrame::iconChanged()
Warning: Object::connect: No such signal QWebFrame::urlChanged(QUrl)
Warning: Object::connect: No such signal QWebPage::loadStarted()
Warning: Object::connect: No such signal QWebPage::loadProgress(int)
Warning: Object::connect: No such signal QWebPage::loadFinished(bool)
Warning: Object::connect: No such signal QWebPage::statusBarMessage(QString)
Warning: Object::connect: No such signal QWebPage::linkClicked(QUrl)
Warning: Object::connect: No such signal QWebPage::selectionChanged()
Warning: Object::connect: No such signal QWebPage::microFocusChanged()
Warning: QMetaObject::invokeMethod: No such method QWebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method QWebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method QWebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method QWebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method QWebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method QWebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method QWebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method QWebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method QWebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method QWebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method QWebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method QWebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method QWebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method QWebPage::repaintRequested(QRect)
Warning: Object::connect: No such signal QWebPage::loadProgress(int)
Errore di segmentazione (core dump creato)

**Comment by giohappy** [comment]
Grazie per la segnalazione @lorex82. Abbiamo riprodotto il crash. Su Windows, con QGIS 2.16, funziona correttamente, adesso verifichiamo come mai su Ubuntu avvenga questo errore.

**Comment by giohappy** [comment]
Purtroppo è un problema comune anche ad altri plugin. Sembra un problema nell'impacchettamento di QGIS 2.16 per Linux, infatti con QGIS 2.18 il problema non appare.
Non so se sia risolvibile...

**Comment by giohappy** [comment]
Problema analogo per QuickOSM: https://github.com/3liz/QuickOSM/issues/84

**Comment by lorex82** [comment]
Confermo, aggiornando alla 2.18 funziona!
